/**
 * Published lookup weights — tuned to 96.05% RTP.
 * Generated by scripts/tune_weights.mjs (do not edit by hand).
 */

export const LOOKUP_META = {
  targetRtp: 0.9604999999999997,
  alpha: 0.6725650300665085,
  weightScale: '281474976710656',
  pathsPerBucket: 3,
};

/** Per-bucket probabilities (sum = 1). Bucket index matches paytable. */
export const LOOKUP_PROBS = [
  3.11159541959146e-7,
  0.00004396914110058774,
  0.0007121881081539771,
  0.018405969937117714,
  0.48083756165408564,
  0.48083756165408564,
  0.018405969937117714,
  0.0007121881081539771,
  0.00004396914110058774,
  3.11159541959146e-7,
];

/** Stake-style uint64 weights (same ratios as LOOKUP_PROBS). */
export const LOOKUP_WEIGHTS_UINT = [
  87583625n,
  12376212967n,
  200463131156n,
  5180819959387n,
  135343741468192n,
  135343741468192n,
  5180819959387n,
  200463131156n,
  12376212967n,
  87583625n,
];
