/**
 * Tune symmetric lookup weights to GAME.targetRtpPercent.
 * Shape prior: binomial(bucket) / payout^alpha; alpha bisected for RTP.
 *
 * Usage: node scripts/tune_weights.mjs
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { GAME, PATHS_PER_BUCKET, PAYTABLE } from '../js/config.js';
import { multToPayoutInt, simIdFromBucket } from '../js/bookMath.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const TARGET_RTP = GAME.targetRtpPercent / 100;
const WEIGHT_SCALE = 2n ** 48n;

function binomial(n, k) {
  if (k < 0 || k > n) return 0;
  let c = 1;
  for (let i = 0; i < k; i += 1) c = (c * (n - i)) / (i + 1);
  return c;
}

function binomialProbs(rows) {
  const denom = 2 ** rows;
  return Array.from({ length: rows + 1 }, (_, k) => binomial(rows, k) / denom);
}

function rtpForAlpha(alpha, paytable, binom) {
  const raw = binom.map((p, i) => p / Math.max(paytable[i], 0.1) ** alpha);
  const sum = raw.reduce((a, x) => a + x, 0);
  const probs = raw.map((x) => x / sum);
  return probs.reduce((r, p, i) => r + p * paytable[i], 0);
}

function solveAlpha(paytable, binom, targetRtp) {
  let lo = 0;
  let hi = 6;
  for (let i = 0; i < 80; i += 1) {
    const mid = (lo + hi) / 2;
    if (rtpForAlpha(mid, paytable, binom) > targetRtp) lo = mid;
    else hi = mid;
  }
  return (lo + hi) / 2;
}

function buildLookup(alpha, paytable, binom) {
  const raw = binom.map((p, i) => p / Math.max(paytable[i], 0.1) ** alpha);
  const sum = raw.reduce((a, x) => a + x, 0);
  const probs = raw.map((x) => x / sum);
  const weights = probs.map((p) => BigInt(Math.round(p * Number(WEIGHT_SCALE))));
  const rtp = probs.reduce((r, p, i) => r + p * paytable[i], 0);
  return { alpha, probs, weights, rtp };
}

const binom = binomialProbs(GAME.rows);
const alpha = solveAlpha(PAYTABLE, binom, TARGET_RTP);
const lookup = buildLookup(alpha, PAYTABLE, binom);

const js = `/**
 * Published lookup weights — tuned to ${GAME.targetRtpPercent}% RTP.
 * Generated by scripts/tune_weights.mjs (do not edit by hand).
 */

export const LOOKUP_META = {
  targetRtp: ${lookup.rtp},
  alpha: ${lookup.alpha},
  weightScale: '${WEIGHT_SCALE}',
  pathsPerBucket: ${PATHS_PER_BUCKET},
};

/** Per-bucket probabilities (sum = 1). Bucket index matches paytable. */
export const LOOKUP_PROBS = [
${lookup.probs.map((p) => `  ${p},`).join('\n')}
];

/** Stake-style uint64 weights (same ratios as LOOKUP_PROBS). */
export const LOOKUP_WEIGHTS_UINT = [
${lookup.weights.map((w) => `  ${w}n,`).join('\n')}
];
`;

writeFileSync(join(__dirname, '../js/weights.js'), js);

const csvLines = ['id,probability_uint64,payout_multiplier'];
lookup.probs.forEach((p, bucket) => {
  const perPath = p / PATHS_PER_BUCKET;
  const perPathWeight = BigInt(Math.round(perPath * Number(WEIGHT_SCALE)));
  for (let variant = 0; variant < PATHS_PER_BUCKET; variant += 1) {
    const simId = simIdFromBucket(bucket, variant, PATHS_PER_BUCKET);
    csvLines.push(`${simId},${perPathWeight},${multToPayoutInt(PAYTABLE[bucket])}`);
  }
});
const dataDir = join(__dirname, '../data');
mkdirSync(dataDir, { recursive: true });
writeFileSync(join(dataDir, 'lookUpTable_base_0.csv'), csvLines.join('\n'));

console.log(`RTP: ${(lookup.rtp * 100).toFixed(4)}%`);
console.log(`Alpha: ${lookup.alpha}`);
console.log(
  `Wrote js/weights.js and data/lookUpTable_base_0.csv (${PAYTABLE.length * PATHS_PER_BUCKET} sims, ${PATHS_PER_BUCKET} paths/bucket)`,
);
console.log('Next: node scripts/generate_books.mjs');
lookup.probs.forEach((p, i) => {
  if (p > 0.0001 || PAYTABLE[i] >= 100) {
    console.log(
      `  bucket ${String(i).padStart(2)}  ${String(PAYTABLE[i]).padStart(6)}x  ${(p * 100).toFixed(4).padStart(8)}%  1 in ${Math.round(1 / p).toLocaleString()}`,
    );
  }
});
